// src/project/dsl-types/install.ts
//
// Installation of generated declarations, tsconfig, and gitignore files in kit
// directories.

import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { loadPipelineConfig } from "../../env/config.js";
import { userKitDir } from "../../env/kit-paths.js";
import { errorMessage } from "../../lib/errors.js";
import type { ProfileOverrides } from "../../model/profiles.js";
import { log } from "../../runtime/logging.js";
import { installKitContracts } from "./contracts-package.js";
import {
  copyPublicDeclarations,
  declarationsHash,
  generateDslDeclarations,
  specializeProjectProfileBackends,
} from "./declarations.js";
import {
  GITIGNORE_ENTRIES,
  kitTsconfigPath,
  kitTypesDirectory,
  PIPELINES_SUBDIR,
  type ProjectTypesMetadata,
  projectKitDirs,
} from "./layout.js";

/**
 * Tsconfig for a kit directory: everything is relative to THIS directory.
 *
 * `baseUrl: "."` makes the file location-independent: the same content works for
 * `<project>/.lance-nuit` and `~/.lance-nuit`, whereas a project-anchored path would
 * not survive in the shared directory.
 */
function kitTsconfig(): Record<string, unknown> {
  return {
    compilerOptions: {
      strict: true,
      noEmit: true,
      target: "ES2022",
      module: "NodeNext",
      moduleResolution: "NodeNext",
      baseUrl: ".",
      paths: {
        "@lance-nuit/dsl": [`./.lance-nuit-types/project/dsl.d.ts`],
      },
    },
    include: [`${PIPELINES_SUBDIR}/**/*.ts`],
  };
}

/** The kit directory ignores its own generated files; nothing must be coordinated
 *  with the project `.gitignore`, where `.lance-nuit/` should remain tracked. */
function ensureKitGitignore(kitDir: string): void {
  const path = join(kitDir, ".gitignore");
  const existing = existsSync(path) ? readFileSync(path, "utf8") : "";
  const lines = existing.split("\n").map((line) => line.trim());
  const missing = GITIGNORE_ENTRIES.filter((entry) => !lines.includes(entry));
  if (missing.length === 0) return;
  const header = existing ? "" : "# Generated by lancenuit types install.\n";
  const separator = existing && !existing.endsWith("\n") ? "\n" : "";
  writeFileSync(path, `${existing}${separator}${header}${missing.join("\n")}\n`);
}

/** Install declarations, the vendored contracts package, tsconfig, and
 *  .gitignore in ONE kit directory. */
export function installKitTypes(kitDir: string, profileOverrides: ProfileOverrides = {}): ProjectTypesMetadata {
  const root = resolve(kitDir);
  const sourceHash = declarationsHash(profileOverrides);
  const temporary = mkdtempSync(join(tmpdir(), "lance-nuit-dsl-types-"));
  try {
    generateDslDeclarations(temporary);

    const destination = kitTypesDirectory(root);
    rmSync(destination, { recursive: true, force: true });
    mkdirSync(destination, { recursive: true });
    copyPublicDeclarations(temporary, destination);
    specializeProjectProfileBackends(destination, profileOverrides);
    if (!existsSync(join(destination, "project", "dsl.d.ts"))) {
      throw new Error("Incomplete DSL generation: project/dsl.d.ts is missing");
    }
    writeFileSync(
      join(destination, "package.json"),
      `${JSON.stringify(
        {
          name: "@lance-nuit/project-types",
          private: true,
          types: "./project/dsl.d.ts",
          lanceNuitTypes: { sourceHash },
        },
        null,
        2,
      )}\n`,
    );

    writeFileSync(kitTsconfigPath(root), `${JSON.stringify(kitTsconfig(), null, 2)}\n`);
    // The gitignore comes first: the package directory it excludes is written
    // right after, and a fresh run refuses to start on a dirty tree.
    ensureKitGitignore(root);
    installKitContracts(root);
    return { sourceHash };
  } finally {
    rmSync(temporary, { recursive: true, force: true });
  }
}

/** Equip the shared kit directory (`~/.lance-nuit`, or `$PIPELINE_HOME`). */
export function installUserTypes(): ProjectTypesMetadata {
  const dir = userKitDir();
  if (!dir) throw new Error("User kit directory not found: neither $PIPELINE_HOME nor HOME is set.");
  mkdirSync(join(dir, PIPELINES_SUBDIR), { recursive: true });
  return installKitTypes(dir);
}

/**
 * Profile backends to inject into declarations WITHOUT being able to block
 * installation.
 *
 * Config only specializes `ProjectProfileBackends` here for autocomplete. Letting
 * it throw created a dead end: typecheck redirected to an unavailable installer, which
 * failed while reading config before generating declarations. The first run—not
 * installation tooling—should be where invalid config stops execution.
 */
function installTimeProfileOverrides(root: string): ProfileOverrides {
  try {
    return loadPipelineConfig(root).profiles;
  } catch (e) {
    const reason = errorMessage(e);
    log.warn(`Project config unreadable — declarations generated without profile backends: ${reason}`);
    return {};
  }
}

/**
 * Equip the project's kit directories.
 *
 * Generated declarations and the local TypeScript configuration are installed
 * in the canonical project kit directory.
 */
export function installProjectTypes(projectRoot = process.cwd()): ProjectTypesMetadata {
  const root = resolve(projectRoot);
  const targets = projectKitDirs(root);
  const profileOverrides = installTimeProfileOverrides(root);
  let metadata: ProjectTypesMetadata | undefined;
  for (const target of targets) {
    mkdirSync(target, { recursive: true });
    metadata = installKitTypes(target, profileOverrides);
  }
  return metadata ?? { sourceHash: declarationsHash(profileOverrides) };
}
